// My name is M. Adil Raheel Dated: 14th Feb 2023
let car = "subaru";
let type = "sport";
let color = "black";
let make = "2022";
let country = "Pakistan";
let transmission = "EFI";
let speed = 100;
let airBags = "No";
let brakes = "Yes";
let seats = 4;
const isCar = car == "subaru" ? true : false;
console.log(isCar);
const isType = type == "sport" ? true : false;
console.log(isType);
const isColor = color == "black" ? true : false;
console.log(isColor);
const isMake = make == "2022" ? true : false;
console.log(isMake);
const isCountry = country == "Pakistan" ? true : false;
console.log(isCountry);
const isTransmission = transmission == "non-EFI" ? true : false;
console.log(isTransmission);
const isSpeed = speed == 120 ? true : false;
console.log(isSpeed);
const isAirBags = airBags == "Yes" ? true : false;
console.log(isAirBags);
const isBrakes = brakes == "No" ? true : false;
console.log(isBrakes);
const isSeats = seats == 5 ? true : false;
console.log(isSeats);
